name: idl_dart_tests
version: 1.2.0-dev
publish_to: none

environment:
  sdk: ^3.6.1

dependencies:
  fory:
    path: ../../../dart/packages/fory

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.0.0
  test: ^1.24.0
